# Generated by Django 5.0.1 on 2024-03-02 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptiMods', '0003_alter_user_first_name_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_aspirations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.TextField(blank=True),
        ),
    ]
