# Generated by Django 5.0.1 on 2024-03-03 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OptiMods', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
